apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qnap-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.131  # <--- Put your QNAP IP here
  share: /cea # <--- The share name on your QNAP
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1